name: aheadoftime
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch>=2.0.0
  - torchvision>=0.15.0
  - cudatoolkit=11.8
  - pip:
    - -r requirements.txt
